name: Generate Feature Documentation

on:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  generate-doc:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        working-directory: automation/feature-docs
        run: npm install --no-audit --no-fund

      - name: Generate & publish doc to Notion
        working-directory: automation/feature-docs
        run: node generate-feature-doc.js
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          NOTION_TOKEN:    ${{ secrets.NOTION_TOKEN }}
          NOTION_DB_ID:    ${{ secrets.NOTION_DB_ID }}
          GITHUB_TOKEN:    ${{ secrets.GITHUB_TOKEN }}
          REPO_FULL:       ${{ github.repository }}
          PR_NUMBER:       ${{ github.event.pull_request.number }}